Fix x64 compiler error C2440: cannot convert from 'LPCTSTR' to 'ATL::CW2A'. Fix x64 compiler error C2664: cannot convert parameter 1 from 'BSTR' to 'LPCTSTR'. Fix line endings.